Maniac/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MarketPlace.urls")),
    path('market/', include("MarketPlace.urls")),
    path('catalogofartists/', include("CatalogOfArtists.urls")),
    path('onlinemedia/', include("OnlineMedia.urls")),
    path('account/', include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineMedia/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views, form_creator, form_editor

urlpatterns = [
    # path('', views.article_list, name='index-media'),
    # path('<str:id_sec>/', views.article_list),

    #Просмотр статей
    path('news/<str:id_news>/', views.news_detail, name='news-media'),
    path('section/<str:id_sec>/detail/<str:id_art>/', views.article_detail, name='detail-media'),
    path('section/<str:id_sec>/tag/<str:id_tag>/', views.article_list, name='index-media'),
    path('page_not_found/', views.page_not_found, name="page-not-found"),

    # Для редактирования старой статьи
    path('publish/<str:id_project>', form_creator.mediaform, name='form-publish'),  # Для публикации новой статьи
    path('post/<str:id_project>', form_creator.post, name='form-post'),

    # Для редактирования старой статьи
    path('project/<str:id_project>/edit/<str:id_article>', form_editor.mediaform_editor, name='form-edit'),
    path('project/<str:id_project>/edit-post/<int:id_article>', form_editor.post_edit, name='form-edit-post'),
]

OnlineMedia/models.py
from django.db import models
from account.models import Project
from embed_video.fields import EmbedVideoField


ID = 1


class Tag(models.Model):
    tag_name = models.CharField(max_length=50,
                                unique=True,
                                verbose_name="Название тега")

    tag_desc = models.CharField(max_length=255,
                                verbose_name="Описание тега")

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def __str__(self):
        return self.tag_name


class News(models.Model):
    news_header = models.CharField(max_length=50,
                                   unique=True,
                                   verbose_name="Краткая статья")

    news_text = models.TextField(unique=True,
                                 verbose_name="Текст новости")

    news_date = models.DateField(verbose_name="Дата новости")

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

    def __str__(self):
        return self.news_header


class Section(models.Model):
    section_name = models.CharField(max_length=80,
                                    unique=True,
                                    help_text="Название раздела",
                                    verbose_name="Раздел")

    section_name_eng = models.CharField(max_length=80,
                                        default="name",
                                        help_text="Название раздела",
                                        verbose_name="Раздел на инглише")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.section_name
        

class Article(models.Model):
    id_section = models.ForeignKey(Section,
                                   on_delete=models.CASCADE,
                                   help_text="Идентификатор категории",
                                   verbose_name="Категория",
                                   blank=True,
                                   null=True)

    id_project = models.ForeignKey(Project,
                                   on_delete=models.CASCADE,
                                   help_text="Идентификатор проекта",
                                   verbose_name="Проект",
                                   blank=True,
                                   null=True)

    # id_type = models.ForeignKey(Types, on_delete = models.SET_NULL, verbose_name="Вид статьи", null = True)
    title = models.TextField(max_length=80,
                             help_text="Заголовок статьи",
                             verbose_name="Заголовок")

    preview_text = models.TextField(max_length=300,
                                    help_text="Краткое описание",
                                    verbose_name="Краткое описание")

    preview_img = models.ImageField(help_text="Картинка для статьи в списке",
                                    upload_to="images/article_img",
                                    verbose_name="Картинка")

    text = models.TextField(max_length=3000,
                            help_text="Полный текст статьи",
                            verbose_name="Текст")

    create_date = models.DateField(help_text="Дата написания статьи",
                                   verbose_name="Дата",
                                   auto_now_add=True,)

    create_time = models.TimeField(help_text="Время написания статьи",
                                   verbose_name="Время",
                                   auto_now_add=True,)

    tag = models.ManyToManyField(to="Tag")

    views = models.IntegerField(default=0,
                                help_text="Просмотры")

    parts = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self):
        return self.title  # self.id_project.name +" "+ self.title

# ниже элементы статьи


class Image(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    image = models.ImageField(upload_to="images/article_img",
                              help_text="Картинка")

    about = models.TextField(verbose_name="Заголовок",
                             max_length=300)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Картинка"
        verbose_name_plural = "Картинки"

    def __str__(self):
        return str(self.image)


class Header(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    text = models.CharField(verbose_name="Заголовок",
                            max_length=200)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Заголовок"
        verbose_name_plural = "Заголовки"

    def __str__(self):
        return str(self.text)


class Paragraph(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    text = models.TextField(verbose_name="Параграф",
                            max_length=3000)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Абзац"
        verbose_name_plural = "Абзацы"

    def __str__(self):
        return str(self.text)


class Quote(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    quote = models.TextField(verbose_name="Цитата",
                             max_length=1000)

    quoter = models.TextField(verbose_name="Кто сказал",
                              max_length=100)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Цитата"
        verbose_name_plural = "Цитаты"

    def __str__(self):
        return str(self.quote)


class Video(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    link = EmbedVideoField(max_length=200,
                           help_text='Ссылка на видеозапись',
                           verbose_name='Ссылка на видеозапись')

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Видео"
        verbose_name_plural = "Видео"

    def __str__(self):
        return str(self.link)

OnlineMedia/forms.py
from django import forms


class ArticleHeader(forms.Form):

    CHOICES = [('Articles', 'Статья'),
               ('Authors', 'Авторский материал'),
               ('Marketing', 'Маркетинговый пост'),
               ('Events', 'Событие'),
               ('Roсkhistory', 'История рока'), ]

    category = forms.ChoiceField(
        choices=CHOICES, 
        widget=forms.RadioSelect,
        required=True,
    )

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type': "input",
                'class': "form-control mb-2 mr-sm-2",
                'id': "inlineFormInputName2",
                'style': "width: 600px;",
                'placeholder': "Заголовок статьи",

            }
        ), 
        max_length = 200
    )

    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'type' : "file", 
                'class':"",
                'id':"inlineFormInputName2", 
                'placeholder':"Изображение"
            }
        )
    )

    preview_text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'type' : "text", 
                'class':"form-control", 
                'id':"inlineFormInputName2", 
                'placeholder':"Описание",
                'style' : "resize: none;",
                'cols':"100",
                'rows':"3",

            }
        ), 
        max_length = 300,
    )

    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'type' : "text", 
                'class':"form-control", 
                'id':"inlineFormInputName2", 
                'placeholder':"Абзац",
                'style' : "resize: none;",
                'cols':"180",
                'rows':"10",

            }
        ), 
        max_length = 1000,
    )

# class Header(forms.Form):
#     header = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'type' : "input", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "width: 600px;",
#                 'placeholder':"Заголовок",
#             }
#         ), 
#         max_length = 200
#     )

# class Paragraph(forms.Form):
#     paragraph = forms.CharField(
#         widget=forms.Textarea(
#             attrs={
#                 'type' : "text", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "resize: none;",
#                 'placeholder':"Абзац",
#             }
#         ), 
#         max_length = 3000
#     )

# class Image(forms.Form):
#     image = forms.ImageField(
#         widget=forms.FileInput(
#             attrs={
#                 'type' : "file", 
#                 'class':"",
#                 'id':"inlineFormInputName2", 
#                 'placeholder':"Изображение"
#             }
#         )
#     )

# class Quote(forms.Form):
#     quote = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'type' : "input", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "width: 1000px;",
#                 'placeholder':"Цитата",
#             }
#         ), 
#         max_length = 200
#     )

# class Video(forms.Form):
#     quote = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'type' : "input", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "width: 1000px;",
#                 'placeholder':"Видео",
#             }
#         ), 
#         max_length = 200
#     )

OnlineMedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Article, Section, News, Tag, Image, Header, Paragraph, Quote, Video
# from django.views.generic import View,DetailView,ListView
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.template.defaulttags import register


@register.filter  # добавляем фильтр для шаблонизатора Пример добавления к декоратору
def get_range(value):
    return list(range(value))


def article_list(request, id_sec="all", id_tag="none"):
    # Костыльно считаем число статей в секциях
    # Индексы к секциям идут строго по порядку
    url_section = id_sec
    
    if id_tag != "none":
        tag = Tag.objects.get(id=id_tag)

    if id_sec == "all":
        if id_tag != "none":
            articles = Article.objects.order_by('-create_date', '-create_time').filter(tag=tag)
        else:
            articles = Article.objects.order_by('-create_date', '-create_time')
    else:
        id_sec = Section.objects.get(section_name_eng=id_sec)
        # Переопределяем переменную чтобы по ключу секции взять нужные картинки
        
        if id_tag != "none":
            articles = Article.objects.filter(id_section=id_sec).order_by('create_date').order_by('create_time')\
                .filter(tag=tag)
        else:
            articles = Article.objects.filter(id_section=id_sec).order_by('create_date').order_by('create_time')
    
    # Пагинация

    page = request.GET.get('page')
    paginator = Paginator(articles, 3)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    # Пагинация

    tags = []
    for article in articles:
        for tag in article.tag.all():
            if not(tag in tags):
                tags.append(tag)

    sections = Section.objects.all()  # Берём все секции и новости
    news = News.objects.order_by('-news_date')[:3]
    template = 'smi.html'

    context = {
        'sections': sections,
        'articles': articles,
        'news': news,
        'tags': tags,
        'url_section': url_section,
        'MEDIA_URL': settings.MEDIA_URL,
    }
    return render(request, template, context)


def article_detail(request, id_art, id_sec):
    sections = Section.objects.all()
    news = News.objects.order_by('-news_date')[:3]
    try:
        article = Article.objects.get(id=id_art)
    except():
        return HttpResponseRedirect('page_not_found')
    article.views = article.views+1
    article.save()

    images = Image.objects.filter(id_article=id_art)
    headers = Header.objects.filter(id_article=id_art)
    paragraphs = Paragraph.objects.filter(id_article=id_art)
    quotes = Quote.objects.filter(id_article=id_art)
    videos = Video.objects.filter(id_article=id_art)
    tags = Tag.objects.all()[:20]

    template = 'smi-detail.html'

    for item in videos:
        item.link = item.link.replace('watch?v=', 'embed/')

    context = {
        'sections': sections,
        'article': article,
        'news': news,
        'images': images,
        'headers': headers,
        'paragraphs': paragraphs,
        'quotes': quotes,
        'videos': videos,
        'tags': tags,
        'url_section': id_sec,
        'MEDIA_URL': settings.MEDIA_URL,
    }
    return render(request, template, context)


def news_detail(request, id_news):

    news_item = News.objects.get(id=id_news)
    news = News.objects.order_by('-news_date')[:3]
    tags = Tag.objects.all()[:20]
    template = 'news-detail.html'
    sections = Section.objects.all()

    context = {
        'sections': sections,
        'news_item': news_item,
        'news': news,
        'tags': tags,
        # 'MEDIA_URL' : settings.MEDIA_URL,
    }
    return render(request, template, context)


def page_not_found(request):
    news = News.objects.order_by('-news_date')[:3]
    sections = Section.objects.all()
    tags = Tag.objects.all()[:20]

    context = {
        'news': news,
        'sections': sections,
        'tags': tags,
    }
    template = "page_not_found.html"
    return render(request, template, context)

# class Article_List(ListView):
#     model = Articles

# Create your views here.

OnlineMedia/templates/news-detail.html
{% extends 'wrapper.html' %}

{% block content %}
        <section class="section menu">
            <div class="container">
                <div class="menu-wrap">
                    <div class="menu-nav">
                        <a href="{% url 'list-category' %}" class="menu__link">Маркетплейс</a>
                        <a href="{% url 'index-catalog' %}" class="menu__link">Каталог артистов</a>
                        <a href="{% url 'index-media' 'all' 'none' %}" class="menu__link">Статьи</a>
                        <a href="#" class="menu__link">Афиша</a>
                        <a href="#" class="menu__link">Мерч</a>
                    </div>
                    <div class="menu-search">
                        <i class="fa fa-search"></i>
                    </div>
                </div>
                <div class="hero">
                    <div class="container">
                        <h1 class="hero__title">{{news_item.news_header}}</span>
                        </h1>
                    </div>
                </div>
            </div>
        </section>
    </header>

    <section class="section smi">
        <div class="container">
            <div class="smi-wrap">
                <div class="smi-content">

                    <div class="smi-item">
                        {% comment %} <div class="smi-item__img">
                            <img src="{{MEDIA_URL}}{{article.preview_img}}" alt="">
                        </div> {% endcomment %}
                        <div class="smi-item__text">
                            {{news_item.news_text|safe}}
                        </div>
                    </div>



                </div>
                <div class="smi-sidebar">
                    <section class="smi-news">
                        {% for item in news%}
                            <div class="smi-news__item">
                                <div class="smi-news__date">{{item.news_date}}</div>
                                <div class="smi-news__text"><a href="{% url 'news-media' item.id %}">{{item.news_header}}</a></div>
                            </div>
                        {% endfor %}
                    </section>
                    <div class="section smi-menu">
                        <div class="smi-menu__wrap">
                            <ul class="smi-menu__list">
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.0.section_name_eng 'none' %}"><i class="fa fa-file-text-o"
                                            aria-hidden="true"></i>{{sections.0.section_name}}<span>{{sections.0.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.1.section_name_eng 'none' %}"><i class="fa fa-check-square-o"
                                            aria-hidden="true"></i>{{sections.1.section_name}}<span>{{sections.1.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.2.section_name_eng 'none' %}"><i class="fa fa-lightbulb-o"
                                            aria-hidden="true"></i>{{sections.2.section_name}}<span>{{sections.2.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.3.section_name_eng 'none' %}"><i class="fa fa-address-book-o"
                                            aria-hidden="true"></i>{{sections.3.section_name}}<span>{{sections.3.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.4.section_name_eng 'none' %}"><i class="fa fa-hashtag"
                                            aria-hidden="true"></i>{{sections.4.section_name}}<span>{{sections.4.article_set.count}}</span></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="section smi-tags">
                        <div class="smi-tags__wrap">
                            {% for tag in tags %}
                                <a href="{% url 'index-media' 'all' tag.id %}" class="smi-tags__item">{{tag.tag_name}}</a>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

OnlineMedia/templates/page_not_found.html
{% extends 'wrapper.html' %}

{% block content %}
        <section class="section menu">
            <div class="container">
                <div class="menu-wrap">
                    <div class="menu-nav">
                        <a href="{% url 'list-category' %}" class="menu__link">Маркетплейс</a>
                        <a href="{% url 'index-catalog' %}" class="menu__link">Каталог артистов</a>
                        <a href="{% url 'index-media' 'all' 'none' %}" class="menu__link">Статьи</a>
                        <a href="#" class="menu__link">Афиша</a>
                        <a href="#" class="menu__link">Мерч</a>
                    </div>
                    <div class="menu-search">
                         {% if request.user.is_authenticated %}<a href="{% url 'profile' %}" class="menu__link">Профиль</a>
                                                              <a href="{% url 'logout' %}" class="menu__link">Выйти</a>
                                                    {% else %}<a href="{% url 'login' %}" class="menu__link">Войти</a>{% endif %}
                        <i class="fa fa-search"></i>
                    </div>
                </div>
                <div class="hero">
                    <div class="container">
                        <h1 class="hero__title">Страница не найдена</span>
                        </h1>
                    </div>
                </div>
            </div>
        </section>
    </header>
                </div>
                <div class="smi-sidebar">
                    <section class="smi-news">
                        {% for item in news%}
                            <div class="smi-news__item">
                                <div class="smi-news__date">{{item.news_date}}</div>
                                <div class="smi-news__text"><a href="{% url 'news-media' item.id %}">{{item.news_header}}</a></div>
                            </div>
                        {% endfor %}
                    </section>
                    <div class="section smi-menu">
                        <div class="smi-menu__wrap">
                            <ul class="smi-menu__list">
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.0.section_name_eng 'none' %}"><i class="fa fa-file-text-o"
                                            aria-hidden="true"></i>{{sections.0.section_name}}<span>{{sections.0.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.1.section_name_eng 'none' %}"><i class="fa fa-check-square-o"
                                            aria-hidden="true"></i>{{sections.1.section_name}}<span>{{sections.1.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.2.section_name_eng 'none' %}"><i class="fa fa-lightbulb-o"
                                            aria-hidden="true"></i>{{sections.2.section_name}}<span>{{sections.2.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.3.section_name_eng 'none' %}"><i class="fa fa-address-book-o"
                                            aria-hidden="true"></i>{{sections.3.section_name}}<span>{{sections.3.article_set.count}}</span></a></li>
                                <li class="smi-menu__items"><a href="{% url 'index-media' sections.4.section_name_eng 'none' %}"><i class="fa fa-hashtag"
                                            aria-hidden="true"></i>{{sections.4.section_name}}<span>{{sections.4.article_set.count}}</span></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="section smi-tags">
                        <div class="smi-tags__wrap">
                            {% for tag in tags %}
                                <a href="{% url 'index-media' url_section tag.id %}" class="smi-tags__item">{{tag.tag_name}}</a>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

OnlineMedia/templates/wrapper.html
<!DOCTYPE html>
<html lang="ru">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rock Stars</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Scada:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="https://use.fontawesome.com/ecc41221c2.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
        <header class="header">
        <div class="adv">
            <div class="container">
                <div class="adv-wrap">
                    <div class="logo logo__img">
                        <img src="{% static 'img/logo-white.png' %}" alt="">
                    </div>
                    <div class="banner banner__img">
                    </div>
                </div>
            </div>
        </div>
        </div>
        <!-- /.adv -->
        <div class="navbar"></div>
        <!-- /.navbar -->

    {% block content %}
    {% endblock %}


    <footer class="footer">
        <div class="container">
            <div class="footer-wrap">
                <div class="footer__logo">
                    <img src="{% static 'img/logo-white.png' %}" alt="" class="logo__img">
                </div>
                <div class="footer__about">&copy;&nbsp;rockstars</div>
                <div class="footer__menu1">
                    <ul class="footer__list">
                        <li class="footer__item"><a href="{% url 'list-category' %}">Маркетплейс</a></li>
                        <li class="footer__item"><a href="{% url 'index-catalog' %}">Каталог артистов</a></li>
                        <li class="footer__item"><a href="{% url 'index-media' 'all' 'none' %}">Статьи</a></li>
                    </ul>
                </div>
                <div class="footer__menu2">
                    <ul class="footer__list">
                        <li class="footer__item"><a href="#">Афиша</a></li>
                        <li class="footer__item"><a href="#">Мерч</a></li>
                    </ul>
                </div>
                <div class="footer__menu3">
                    <ul class="footer__list">
                        <li class="footer__item"><a href="#">О проекте</a></li>
                        <li class="footer__item"><a href="#">Прислать статью</a></li>
                        <li class="footer__item"><a href="#">Реклама на сайте</a></li>
                    </ul>
                </div>
                <div class="footer__sociallinks">
                    <a href="#"><i class="fa fa-vk" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>