CatalogOfArtists/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index-catalog'),
    path('genres_list/<int:pk>/', views.genre_detail_view, name='genre-detail'),
    path('artists_list/<int:pk>/', views.artist_detail_view, name='artist-card'),
]

Maniac/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MarketPlace.urls")),
    path('market/', include("MarketPlace.urls")),
    path('catalogofartists/', include("CatalogOfArtists.urls")),
    path('onlinemedia/', include("OnlineMedia.urls")),
    path('account/', include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CatalogOfArtists/models.py
from django.db import models
from embed_video.fields import EmbedVideoField


class Genres(models.Model):
    GenreName = models.CharField(max_length=50, help_text='Жанр', verbose_name='Жанр')

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'

    def __str__(self):
        return self.GenreName


class Cities(models.Model):
    CityName = models.CharField(max_length=60, help_text='Город', verbose_name='Город')

    class Meta:
        verbose_name = 'город'
        verbose_name_plural = 'города'

    def __str__(self):
        return self.CityName


class Relase(models.Model):
    fk_artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=40, verbose_name='Название релиза')
    image = models.ImageField(upload_to='images/photo_relases', blank=True, verbose_name='Изображение')
    age = models.CharField(max_length=4, verbose_name='Год выхода келиза')

    class Meta:
        verbose_name = 'релиз'
        verbose_name_plural = 'релизы'

    def __str__(self):
        return self.name


class Group_Members(models.Model):
    fk_artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, verbose_name='Фамилия, имя артиста')
    role = models.CharField(max_length=50, verbose_name='Роль музыканта в группе')

    class Meta:
        verbose_name = 'состав'
        verbose_name_plural = 'составы'

    def __str__(self):
        return self.name


class Management(models.Model):
    fk_artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    LPRname = models.CharField(max_length=100, help_text='Имя ЛПР (менеджер, директор и т.д.', verbose_name='Имя ЛПР')
    role = models.CharField(max_length=50, blank=True, help_text='Должность', verbose_name='Должность')
    LPRphone = models.CharField(max_length=13, help_text='Номер телефона ЛПР', verbose_name='Номер ЛПР')
    LPRemail = models.EmailField(help_text='Email ЛПР', null=True, verbose_name='email ЛПР')
    LPRlink = models.CharField(max_length=100, help_text='Cсылка на ЛПР', verbose_name='Ссылка ЛПР')

    class Meta:
        verbose_name = 'менеджмент'
        verbose_name_plural = 'менеджмент'


class Gallery(models.Model):
    fk_artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/gallery_artists', blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'галерея'
        verbose_name_plural = 'галерея'


class Videos(models.Model):
    fk_artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    link = EmbedVideoField(max_length=200, help_text='Ссылка на видеозапись', verbose_name='Ссылка на видеозапись')

    class Meta:
        verbose_name = 'видеозапись'
        verbose_name_plural = 'видеозаписи'


class Poster(models.Model):
    fk_artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/posters_artists', blank=True, verbose_name='Изображение')
    date = models.DateField(null=True, blank=True, verbose_name='Дата')

    class Meta:
        verbose_name = 'афиша'
        verbose_name_plural = 'афиша'


class Artists(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField(upload_to='images/photo_group', blank=True, verbose_name='Изображение')
    main_genre = models.ForeignKey(Genres, on_delete=models.SET_NULL, null=True, max_length=100,
                                   help_text='Введите основной жанр', verbose_name='Основной жанр',
                                   related_name='main_genre')
    genre = models.ManyToManyField(Genres, help_text='Выберите жанры', verbose_name='Жанры', related_name='genre')
    year_of_found = models.DateField(null=True, blank=True, verbose_name='Дата основания')
    city = models.ForeignKey('Cities', on_delete=models.SET_NULL, null=True, verbose_name='Город')
    text = models.TextField(max_length=10000, help_text='Введите информацию об артисте', verbose_name='Информация')
    vklink = models.CharField(max_length=100, help_text='ВК ссылка на артиста', verbose_name='Ссылка на вк')
    websitelink = models.CharField(max_length=100, help_text='Ссылка на сайт артиста', verbose_name='Веб-сайт')
    LPRname = models.CharField(max_length=100, help_text='Имя ЛПР (менеджер, директор и т.д.', verbose_name='Имя ЛПР')
    role = models.CharField(max_length=50, blank=True, help_text='Должность', verbose_name='Должность')
    LPRphone = models.CharField(max_length=13, help_text='Номер телефона ЛПР', verbose_name='Номер ЛПР')
    LPRemail = models.EmailField(help_text='Email ЛПР', null=True, verbose_name='email ЛПР')
    LPRlinkvk = models.CharField(max_length=100, help_text='ВК ссылка на ЛПР', verbose_name='Ссылка на вк ЛПР')
    feedback = models.BooleanField(default=True, verbose_name='Форма обратной связи')
    linkYandexM = models.CharField(max_length=100, blank=True, help_text='Ссылка на Яндекс.Музыка',
                                   verbose_name='Ссылка на Яндекс.Музыка')
    linkGoogleP = models.CharField(max_length=100, blank=True, help_text='Ссылка на Google Music',
                                   verbose_name='Ссылка на Google Music')
    linkAppleM = models.CharField(max_length=100, blank=True, help_text='Ссылка на Apple Music',
                                   verbose_name='Ссылка на Apple Music')
    linkYoutubeM = models.CharField(max_length=100, blank=True, help_text='Ссылка на YouTube Music',
                                   verbose_name='Ссылка на YouTube Music')
    linksite = models.CharField(max_length=100, blank=True, help_text='Ссылка на site',
                                    verbose_name='Ссылка на site')
    linkvk = models.CharField(max_length=100, blank=True, help_text='Ссылка на VK',
                                    verbose_name='Ссылка на VK')
    linkyoutube = models.CharField(max_length=100, blank=True, help_text='Ссылка на YouTube',
                                    verbose_name='Ссылка на YouTube')
    linkinsta = models.CharField(max_length=100, blank=True, help_text='Ссылка на Instagram',
                                    verbose_name='Ссылка на Instagram')
    linkfacebook = models.CharField(max_length=100, blank=True, help_text='Ссылка на Facebook',
                                    verbose_name='Ссылка на Facebook')

    class Meta:
        verbose_name = 'артист'
        verbose_name_plural = 'артисты'

    def __str__(self):
        return self.name

    def display_genre(self):
        return ', '.join([genre.GenreName for genre in self.genre.all()[:2]])

    display_genre.short_description = 'Жанр'

CatalogOfArtists/forms.py
from django import forms


class EmailPostForm(forms.Form):
    topic = forms.CharField(label='', max_length=25, widget=forms.TextInput(attrs={'placeholder' : 'Ваше имя'}))
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder' : 'Ваше email'}))
    text = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder' : 'текст'}))

CatalogOfArtists/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.mail import send_mail
from .models import Cities, Artists, Genres, Gallery, Videos, Poster
from .forms import EmailPostForm
import itertools


def index(request):
    genre = Genres.objects.all()
    artist = Artists.objects.all()
    i = 1
    var = ''
    for item in artist:
        var += item.name[0]
    # var = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
    var = sorted(var)
    var = ''.join(ch for ch, _ in itertools.groupby(var))

    return render(
        request,
        'index.html',
        context={'genre': genre,
                 'artist': artist,
                'var': var,
        }
    )


def genre_detail_view(request, pk):
    artist = Artists.objects.filter(genre=pk).all()[:8]
    genre = Genres.objects.get(id=pk)
    template_name = 'genres_detail.html'

    return render(
        request,
        template_name,
        context={'genre': genre,
                 'artist': artist,
        }
    )


def artist_detail_view(request, pk):
    artist = Artists.objects.get(id=pk)
    gallery = Gallery.objects.filter(fk_artist=artist).all()
    posters = Poster.objects.filter(fk_artist=artist).all().order_by('-date')
    videos = Videos.objects.filter(fk_artist=artist).all()
    flaglink = True
    template_name = 'artists_card.html'
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            topic = 'Сообщение от пользователя сайта ({})'.format(cd['topic'])
            message = '{}\nОтвет по адресу {}'.format(cd['text'], cd['email'])
            send_mail(topic, message, 'testdjangos@gmail.com', [artist.LPRemail])
            return redirect('artist-card', pk)
        form = EmailPostForm()

    else:
        form = EmailPostForm()

    for item in videos:
        item.link = item.link.replace('watch?v=', 'embed/')


    if (artist.linkvk != '' or
        artist.linksite != '' or
        artist.linkvk != '' or
        artist.linkyoutube != '' or
        artist.linkinsta != '' or
        artist.linkfacebook != ''):
            flaglink = False



    context = {
        'artist': artist,
        'form': form,
        'flaglink': flaglink,
        'gallery': gallery,
        'videos': videos,
        'posters': posters,
    }
    return render(request, template_name, context)


# def artists_views(request):
#     artists = Artists.objects.all()
#     i = 1
#     var = ''
#     for item in artists:
#         var += item.name[0]
#     # var = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
#     var = sorted(var)
#     var = ''.join(ch for ch, _ in itertools.groupby(var))
#
#     context = {
#         'artists': artists,
#         'var': var,
#     }
#     template_name = 'artists_card.html'
#
#     return render(request, template_name, context)

CatalogOfArtists/templates/artists_card.html
{% extends 'main.html' %}

{% load static %}
{% load embed_video_tags %}

{% block title %}{{ artist.name }} | RS{% endblock %}

{% block search %}
{% endblock %}

{% block content %}
<section class="ac-header">
    <div class="container-fullscreen">
        <div class="ac-header__cover">
            <img src="{{ MEDIA_URL }}{{ artist.image }}" alt="" class="ac-header__img">
            <div class="ac-header__header">
                <div class="ac-header__name">
                    <h1>{{ artist.name }}</h1>
                    <span class="ac-header__style">
                        {{ artist.main_genre }}
                    </span>
                </div>
                <div class="ac-header__info">
                    {% if artist.year_of_found != None %}
                    <div class="ac-header__date">
                        Дата основания: {{ artist.year_of_found }}
                    </div>
                    {% endif %}
                    <div class="ac-header__city">
                        {{ artist.city }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="section ac">
    <div class="container">
        <div class="ac__wrapper">
            <div class="ac__content">
                <div class="ac__text">
                    {{ artist.text|safe }}
                </div>
                <div class="ac__albums">
                    <h3>Официальные релизы</h3>
                    <div class="ac__albums-wrapper">
                        {% for relase in artist.relase_set.all|dictsortreversed:'age' %}
                        <div class="ac__albums-column">
                            <div class="ac__albums-item">
                                <div class="ac__albums-cover">
                                    <img src="{{ MEDIA_URL }}{{ relase.image }}" alt="">
                                </div>
                                <div class="ac__albums-title">
                                    {{ relase.name }}
                                </div>
                                <div class="ac__albums-date">
                                    {{ relase.age }}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                </div>

                <div id="lightgallery" >
                    {% for image in gallery %}
                        <div style="display: inline-block; margin-right: 1px;" data-src="{{ MEDIA_URL }}{{ image.image }}">
                            <a href="">
                                <img width="200" class="img-responsive" src="{{ MEDIA_URL }}{{ image.image }}" alt="">
                            </a>
                        </div>
                    {% endfor %}
                </div>

                <div class="ac__video">
                    <h3>Видеозаписи</h3>
                    <div class="ac__video-wrapper">
                        {% for video in videos %}
                        <div class="ac__video-column">
                            <div class="ac__video-item">
                                <iframe width="100%" height="250" src="{{ video.link }}"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen>
                                </iframe>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="ac__concerts">
                    <h3>Предстоящие концерты</h3>
                    <div class="ac__concerts-wrapper">
                        {% for poster in posters %}
                            <div class="ac__concerts-column">
                                <div class="ac__concerts-item">
                                    <img src="{{ MEDIA_URL }}{{ poster.image }}" alt="">
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
            <div class="ac__sidebar">
                <div class="ac__team ac__sidebarblock">
                    <h3>Состав группы</h3>
                    {% for member in artist.group_members_set.all %}
                    <div class="ac__team-member">
                        <div class="ac__team-name">
                            {{ member.name }}
                        </div>
                        <div class="ac__team-role">
                            {{ member.role }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="ac__team ac__sidebarblock">
                    <h3>Менеджмент</h3>
                    <div class="ac__team-member">
                        <div class="ac__team-name">
                            {{ artist.LPRname }}
                        </div>
                        <div class="ac__team-role">
                            {{ artist.role }}
                        </div>
                    </div>
                    <div class="ac__team-phone">
                        {{ artist.LPRphone }}
                    </div>
                    <div class="ac__team-link">
                        <a href="{{ artist.LPRlinkvk }}" target="_blank"> {{ artist.LPRlinkvk  }} </a>
                    </div>
                    <div class="ac__team-email">
                        {{ artist.LPRemail  }}
                    </div>
                    <br>
                    {% for manage in artist.management_set.all %}
                    <div class="ac__team-member">
                        <div class="ac__team-name">
                            {{ manage.LPRname }}
                        </div>
                        <div class="ac__team-role">
                            {{ manage.role }}
                        </div>
                    </div>
                    <div class="ac__team-phone">
                        {{ manage.LPRphone }}
                    </div>
                    <div class="ac__team-link">
                        <a href="{{ artist.LPRlink }}" target="_blank"> {{ manage.LPRlink  }} </a>
                    </div>
                    <div class="ac__team-email">
                        {{ manage.LPRemail  }}
                    </div>
                    <br>
                    {% endfor %}

                    {% if artist.feedback %}
                    <div class="ac__form form">
                        <form action="" method="post">
                            {% csrf_token %}
                                <div class="ac__form-element">
                                    {{ form.topic }}
                                </div>
                                <div class="ac__form-element">
                                    {{ form.email }}
                                </div>
                                <div class="ac__form-element">
                                    {{ form.text }}
                                </div>
                            <input type="submit" class="ac__form-button" value="Отправить">
                        </form>
                    </div>
                    {% endif %}
                </div>

                <div class="ac__links ac__sidebarblock">
                    <h3>Слушать музыку</h3>
                    <ul class="ac__links-list">
                        {% if artist.linkYandexM != "" %}
                            <li><a href="{{ artist.linkYandexM }}">Яндекс музыка</a></li>
                        {% endif %}
                        {% if artist.linkGoogleP != "" %}
                            <li><a href="{{ artist.linkGoogleP }}">Goggle Music</a></li>
                        {% endif %}
                        {% if artist.linkAppleM != "" %}
                            <li><a href="{{ artist.linkAppleM }}">Apple Music</a></li>
                        {% endif %}
                        {% if artist.linkYoutubeM != "" %}
                            <li><a href="{{ artist.linkYoutubeM }}">Youtube Music</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% if not flaglink %}
                <div class="ac__links ac__sidebarblock">
                    <h3>Ссылки</h3>
                    {% if artist.linksite != "" %}
                        <div class="ac__links-element">
                            <div class="ac__links-icon">
                                <i class="fa fa-globe"></i>
                            </div>
                            <div class="ac__links-title">
                                <a href="{{ artist.linksite }}" target="_blank">Сайт {{ artist.name }}</a>
                            </div>
                        </div>
                    {% endif %}
                    {% if artist.linkvk != "" %}
                    <div class="ac__links-element">
                        <div class="ac__links-icon">
                            <i class="fa fa-vk"></i>
                        </div>
                        <div class="ac__links-title">
                            <a href="{{ artist.linkvk }}" target="_blank">Группа ВКонтакте</a>
                        </div>
                    </div>
                    {% endif %}
                    {% if artist.linkyoutube != "" %}
                    <div class="ac__links-element">
                        <div class="ac__links-icon">
                            <i class="fa fa-youtube"></i>
                        </div>
                        <div class="ac__links-title">
                            <a href="{{ artist.linkyoutube }}" target="_blank">Канал
                                на Youtube</a>
                        </div>
                    </div>
                    {% endif %}
                    {% if artist.linkinsta != "" %}
                    <div class="ac__links-element">
                        <div class="ac__links-icon">
                            <i class="fa fa-instagram"></i>
                        </div>
                        <div class="ac__links-title">
                            <a href="{{ artist.linkinsta  }}"
                                target="_blank">Instagram-аккаунт</a>
                        </div>
                    </div>
                    {% endif %}
                    {% if artist.linkfacebook != "" %}
                    <div class="ac__links-element">
                        <div class="ac__links-icon">
                            <i class="fa fa-facebook"></i>
                        </div>
                        <div class="ac__links-title">
                            <a href="{{ artist.linkfacebook }}" target="_blank">Facebook</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

CatalogOfArtists/templates/genres_detail.html
{% extends 'main.html' %}

{% load static %}

{% block search %}
  <h1 class="hero__title">Каталог артистов<br><span>&laquo;Rock Stars&raquo;</span></h1>
  <h3 class="hero__subtitle">Музыкальные коллективы и&nbsp;артисты в&nbsp;жанре тяжелой музыки
      из&nbsp;России</h3>
{% endblock %}

{% block content %}
<section class="section mc">
        <div class="container">
            <h3>{{ genre.GenreName }}</h3>
            <div class="mc__wrapper">
                {% for artist in artist %}
                <div class="mc__column">
                    <a href="{% url 'artist-card' artist.id %}" class="mc__link">
                        <div class="mc__item">
                            <div class="mc__cover">
                                <img src="{{ MEDIA_URL }}{{ artist.image }}" alt="">
                                <span class="mc__title">
                                    {{ artist.name }}
                                </span>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

CatalogOfArtists/templates/index.html
{% extends 'main.html' %}

{% load my_filter %}
{% load static %}

{% block title %}Каталог артистов | RS{% endblock %}

{% block search %}
  <h1 class="hero__title">Каталог артистов<br><span>&laquo;Rock Stars&raquo;</span></h1>
  <h3 class="hero__subtitle">Музыкальные коллективы и&nbsp;артисты в&nbsp;жанре тяжелой музыки
      из&nbsp;России</h3>
{% endblock %}

{% block content %}
<section class="section stylelist">
        <div class="container">
            <div class="stylelist__wrapper">
                <div class="stylelist__listblock">
                    <ul class="stylelist__list">
                    {% for genre in genre %}
                        <li><a href="{% url 'genre-detail' genre.id %}">{{ genre.GenreName }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </section>
<section class="section stylelist">
        <div class="container">
            <div class="stylelist__wrapper">
                <div class="stylelist__listblock">
                    <ul class="stylelist__list">
                    {% if artist %}
                        {% for letter in var %}
                            <h4><strong>{{ letter }}</strong></h4>
                            {% for artist in artist %}
                                {% if artist.name|filter_a:letter == '+' %}
                                <a href="{% url 'artist-card' artist.id %}">{{ artist.name }}</a> <br>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% else %}
                        <p>Артистов в базе нет</p>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </div>

    </section>
    <section class="section mc">
        <div class="container">
            <h3>Новое в каталоге</h3>
            <div class="mc__wrapper">
                {% for artist in artist %}
                <div class="mc__column">
                    <a href="{% url 'artist-card' artist.id %}" class="mc__link">
                        <div class="mc__item">
                            <div class="mc__cover">
                                <img src="{{ MEDIA_URL }}{{ artist.image }}" alt="">
                                <span class="mc__title">
                                    {{ artist.name }}
                                </span>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}