Maniac/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MarketPlace.urls")),
    path('market/', include("MarketPlace.urls")),
    path('catalogofartists/', include("CatalogOfArtists.urls")),
    path('onlinemedia/', include("OnlineMedia.urls")),
    path('account/', include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineMedia/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views, form_creator, form_editor

urlpatterns = [
    # path('', views.article_list, name='index-media'),
    # path('<str:id_sec>/', views.article_list),

    #Просмотр статей
    path('news/<str:id_news>/', views.news_detail, name='news-media'),
    path('section/<str:id_sec>/detail/<str:id_art>/', views.article_detail, name='detail-media'),
    path('section/<str:id_sec>/tag/<str:id_tag>/', views.article_list, name='index-media'),
    path('page_not_found/', views.page_not_found, name="page-not-found"),

    # Для редактирования старой статьи
    path('publish/<str:id_project>', form_creator.mediaform, name='form-publish'),  # Для публикации новой статьи
    path('post/<str:id_project>', form_creator.post, name='form-post'),

    # Для редактирования старой статьи
    path('project/<str:id_project>/edit/<str:id_article>', form_editor.mediaform_editor, name='form-edit'),
    path('project/<str:id_project>/edit-post/<int:id_article>', form_editor.post_edit, name='form-edit-post'),
]

OnlineMedia/models.py
from django.db import models
from account.models import Project
from embed_video.fields import EmbedVideoField


ID = 1


class Tag(models.Model):
    tag_name = models.CharField(max_length=50,
                                unique=True,
                                verbose_name="Название тега")

    tag_desc = models.CharField(max_length=255,
                                verbose_name="Описание тега")

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def __str__(self):
        return self.tag_name


class News(models.Model):
    news_header = models.CharField(max_length=50,
                                   unique=True,
                                   verbose_name="Краткая статья")

    news_text = models.TextField(unique=True,
                                 verbose_name="Текст новости")

    news_date = models.DateField(verbose_name="Дата новости")

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

    def __str__(self):
        return self.news_header


class Section(models.Model):
    section_name = models.CharField(max_length=80,
                                    unique=True,
                                    help_text="Название раздела",
                                    verbose_name="Раздел")

    section_name_eng = models.CharField(max_length=80,
                                        default="name",
                                        help_text="Название раздела",
                                        verbose_name="Раздел на инглише")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.section_name
        

class Article(models.Model):
    id_section = models.ForeignKey(Section,
                                   on_delete=models.CASCADE,
                                   help_text="Идентификатор категории",
                                   verbose_name="Категория",
                                   blank=True,
                                   null=True)

    id_project = models.ForeignKey(Project,
                                   on_delete=models.CASCADE,
                                   help_text="Идентификатор проекта",
                                   verbose_name="Проект",
                                   blank=True,
                                   null=True)

    # id_type = models.ForeignKey(Types, on_delete = models.SET_NULL, verbose_name="Вид статьи", null = True)
    title = models.TextField(max_length=80,
                             help_text="Заголовок статьи",
                             verbose_name="Заголовок")

    preview_text = models.TextField(max_length=300,
                                    help_text="Краткое описание",
                                    verbose_name="Краткое описание")

    preview_img = models.ImageField(help_text="Картинка для статьи в списке",
                                    upload_to="images/article_img",
                                    verbose_name="Картинка")

    text = models.TextField(max_length=3000,
                            help_text="Полный текст статьи",
                            verbose_name="Текст")

    create_date = models.DateField(help_text="Дата написания статьи",
                                   verbose_name="Дата",
                                   auto_now_add=True,)

    create_time = models.TimeField(help_text="Время написания статьи",
                                   verbose_name="Время",
                                   auto_now_add=True,)

    tag = models.ManyToManyField(to="Tag")

    views = models.IntegerField(default=0,
                                help_text="Просмотры")

    parts = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self):
        return self.title  # self.id_project.name +" "+ self.title

# ниже элементы статьи


class Image(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    image = models.ImageField(upload_to="images/article_img",
                              help_text="Картинка")

    about = models.TextField(verbose_name="Заголовок",
                             max_length=300)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Картинка"
        verbose_name_plural = "Картинки"

    def __str__(self):
        return str(self.image)


class Header(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    text = models.CharField(verbose_name="Заголовок",
                            max_length=200)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Заголовок"
        verbose_name_plural = "Заголовки"

    def __str__(self):
        return str(self.text)


class Paragraph(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    text = models.TextField(verbose_name="Параграф",
                            max_length=3000)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Абзац"
        verbose_name_plural = "Абзацы"

    def __str__(self):
        return str(self.text)


class Quote(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    quote = models.TextField(verbose_name="Цитата",
                             max_length=1000)

    quoter = models.TextField(verbose_name="Кто сказал",
                              max_length=100)

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Цитата"
        verbose_name_plural = "Цитаты"

    def __str__(self):
        return str(self.quote)


class Video(models.Model):
    id_article = models.ForeignKey("Article",
                                   verbose_name="Статья",
                                   on_delete=models.CASCADE,
                                   default=ID)

    link = EmbedVideoField(max_length=200,
                           help_text='Ссылка на видеозапись',
                           verbose_name='Ссылка на видеозапись')

    position = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = "Видео"
        verbose_name_plural = "Видео"

    def __str__(self):
        return str(self.link)

OnlineMedia/forms.py
from django import forms


class ArticleHeader(forms.Form):

    CHOICES = [('Articles', 'Статья'),
               ('Authors', 'Авторский материал'),
               ('Marketing', 'Маркетинговый пост'),
               ('Events', 'Событие'),
               ('Roсkhistory', 'История рока'), ]

    category = forms.ChoiceField(
        choices=CHOICES, 
        widget=forms.RadioSelect,
        required=True,
    )

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type': "input",
                'class': "form-control mb-2 mr-sm-2",
                'id': "inlineFormInputName2",
                'style': "width: 600px;",
                'placeholder': "Заголовок статьи",

            }
        ), 
        max_length = 200
    )

    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'type' : "file", 
                'class':"",
                'id':"inlineFormInputName2", 
                'placeholder':"Изображение"
            }
        )
    )

    preview_text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'type' : "text", 
                'class':"form-control", 
                'id':"inlineFormInputName2", 
                'placeholder':"Описание",
                'style' : "resize: none;",
                'cols':"100",
                'rows':"3",

            }
        ), 
        max_length = 300,
    )

    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'type' : "text", 
                'class':"form-control", 
                'id':"inlineFormInputName2", 
                'placeholder':"Абзац",
                'style' : "resize: none;",
                'cols':"180",
                'rows':"10",

            }
        ), 
        max_length = 1000,
    )

# class Header(forms.Form):
#     header = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'type' : "input", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "width: 600px;",
#                 'placeholder':"Заголовок",
#             }
#         ), 
#         max_length = 200
#     )

# class Paragraph(forms.Form):
#     paragraph = forms.CharField(
#         widget=forms.Textarea(
#             attrs={
#                 'type' : "text", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "resize: none;",
#                 'placeholder':"Абзац",
#             }
#         ), 
#         max_length = 3000
#     )

# class Image(forms.Form):
#     image = forms.ImageField(
#         widget=forms.FileInput(
#             attrs={
#                 'type' : "file", 
#                 'class':"",
#                 'id':"inlineFormInputName2", 
#                 'placeholder':"Изображение"
#             }
#         )
#     )

# class Quote(forms.Form):
#     quote = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'type' : "input", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "width: 1000px;",
#                 'placeholder':"Цитата",
#             }
#         ), 
#         max_length = 200
#     )

# class Video(forms.Form):
#     quote = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'type' : "input", 
#                 'class':"form-control mb-2 mr-sm-2", 
#                 'id':"inlineFormInputName2", 
#                 'style' : "width: 1000px;",
#                 'placeholder':"Видео",
#             }
#         ), 
#         max_length = 200
#     )

OnlineMedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Article, Section, News, Tag, Image, Header, Paragraph, Quote, Video
# from django.views.generic import View,DetailView,ListView
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.template.defaulttags import register


@register.filter  # добавляем фильтр для шаблонизатора Пример добавления к декоратору
def get_range(value):
    return list(range(value))


def article_list(request, id_sec="all", id_tag="none"):
    # Костыльно считаем число статей в секциях
    # Индексы к секциям идут строго по порядку
    url_section = id_sec
    
    if id_tag != "none":
        tag = Tag.objects.get(id=id_tag)

    if id_sec == "all":
        if id_tag != "none":
            articles = Article.objects.order_by('-create_date', '-create_time').filter(tag=tag)
        else:
            articles = Article.objects.order_by('-create_date', '-create_time')
    else:
        id_sec = Section.objects.get(section_name_eng=id_sec)
        # Переопределяем переменную чтобы по ключу секции взять нужные картинки
        
        if id_tag != "none":
            articles = Article.objects.filter(id_section=id_sec).order_by('create_date').order_by('create_time')\
                .filter(tag=tag)
        else:
            articles = Article.objects.filter(id_section=id_sec).order_by('create_date').order_by('create_time')
    
    # Пагинация

    page = request.GET.get('page')
    paginator = Paginator(articles, 3)
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    # Пагинация

    tags = []
    for article in articles:
        for tag in article.tag.all():
            if not(tag in tags):
                tags.append(tag)

    sections = Section.objects.all()  # Берём все секции и новости
    news = News.objects.order_by('-news_date')[:3]
    template = 'smi.html'

    context = {
        'sections': sections,
        'articles': articles,
        'news': news,
        'tags': tags,
        'url_section': url_section,
        'MEDIA_URL': settings.MEDIA_URL,
    }
    return render(request, template, context)


def article_detail(request, id_art, id_sec):
    sections = Section.objects.all()
    news = News.objects.order_by('-news_date')[:3]
    try:
        article = Article.objects.get(id=id_art)
    except():
        return HttpResponseRedirect('page_not_found')
    article.views = article.views+1
    article.save()

    images = Image.objects.filter(id_article=id_art)
    headers = Header.objects.filter(id_article=id_art)
    paragraphs = Paragraph.objects.filter(id_article=id_art)
    quotes = Quote.objects.filter(id_article=id_art)
    videos = Video.objects.filter(id_article=id_art)
    tags = Tag.objects.all()[:20]

    template = 'smi-detail.html'

    for item in videos:
        item.link = item.link.replace('watch?v=', 'embed/')

    context = {
        'sections': sections,
        'article': article,
        'news': news,
        'images': images,
        'headers': headers,
        'paragraphs': paragraphs,
        'quotes': quotes,
        'videos': videos,
        'tags': tags,
        'url_section': id_sec,
        'MEDIA_URL': settings.MEDIA_URL,
    }
    return render(request, template, context)


def news_detail(request, id_news):

    news_item = News.objects.get(id=id_news)
    news = News.objects.order_by('-news_date')[:3]
    tags = Tag.objects.all()[:20]
    template = 'news-detail.html'
    sections = Section.objects.all()

    context = {
        'sections': sections,
        'news_item': news_item,
        'news': news,
        'tags': tags,
        # 'MEDIA_URL' : settings.MEDIA_URL,
    }
    return render(request, template, context)


def page_not_found(request):
    news = News.objects.order_by('-news_date')[:3]
    sections = Section.objects.all()
    tags = Tag.objects.all()[:20]

    context = {
        'news': news,
        'sections': sections,
        'tags': tags,
    }
    template = "page_not_found.html"
    return render(request, template, context)

# class Article_List(ListView):
#     model = Articles

# Create your views here.

OnlineMedia/templates/form_creator/fields.html
<div fieldWrapper id="list-elements">
    <div id="uploading">
        {% if case == 1 %}
        <div name="module={{position}}.header">
            <br/>
            <br/>
            Заголовок   
            <br/>
            <input type="input" name="{{position}}.header" class="form-control mb-2 mr-sm-2 {{position}}.header" id="inlineFormInputName2" style="width: 600px;" placeholder="Заголовок" maxlength="200" required=""> 
            <button class="btn btn-danger" onclick = "destroy_object('module={{position}}.header');" >Удалить элемент</button>     
        </div>   
        {% endif %}
        {% if case == 2 %}
        <div name="module={{position}}.paragraph">
            <br/>
            <br/>
            Абзац   
            <br/>
            <textarea name="{{position}}.paragraph" cols="40" rows="10" type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="resize: none;" placeholder="Абзац" maxlength="200" required=""></textarea> 
            <button class="btn btn-danger" onclick = "destroy_object('module={{position}}.paragraph');" >Удалить элемент</button>     
        </div>
        {% endif %}
        {% if case == 3 %}
        <div name="module={{position}}.image">
            <br/>
            <br/>
            Изображение   
            <br/>
            <input type="file" name="{{position}}.image" class="" id="inlineFormInputName2" placeholder="Изображение" accept="image/*" required="">
            <button class="btn btn-danger" onclick = "destroy_object('module={{position}}.image');" >Удалить элемент</button>
        </div>
        {% endif %}
        {% if case == 4 %}
        <div name="module={{position}}.quote">
            <br/>
            <br/>
            Цитата   
            <br/>
            <input type="input" name="{{position}}.quote" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 1000px;" placeholder="Цитата" maxlength="200" required="">
            <button class="btn btn-danger" onclick = "destroy_object('module={{position}}.quote');" >Удалить элемент</button>
        </div>
        {% endif %}
        {% if case == 5 %}
        <div name="module={{position}}.video">
            <br/>
            <br/>
            Видео   
            <br/>
            <input type="input" name="{{position}}.video" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 1000px;" placeholder="Ссылка на видео" maxlength="200" required="">
            <button class="btn btn-danger" onclick = "destroy_object('module={{position}}.video');" >Удалить элемент</button>
        </div>
        {% endif %}
    </div>
    <div id="loading">
        <a class="p-link btn btn-warning" href="?upload=1&position={{position}}">Добавить Заголовок</a>
        <a class="p-link btn btn-warning" href="?upload=2&position={{position}}">Добавить Абзац</a> 
        <a class="p-link btn btn-warning" href="?upload=3&position={{position}}">Добавить Изображение</a>
        <a class="p-link btn btn-warning" href="?upload=4&position={{position}}">Добавить Цитату</a>
        <a class="p-link btn btn-warning" href="?upload=5&position={{position}}">Добавить Видео</a>
    </div>
</div>

OnlineMedia/templates/form_creator/form_editor.html
{% extends "form_creator/form_wrapper.html"%}
{% load static %}
{% block content %}
<h1>Редактирование статьи</h1>
</br>
    <Form method = "POST"  action="{% url 'form-edit-post' project.id id_article %}" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="input-group">
            <div fieldWrapper id="list-elements">
                <div style = "float:right; margin-right:300px;">
                    <h2>Теги</h2>
                    {% for tag in tags %}
                        {% if tag in article_tags %}
                            <input type="checkbox" name="tag" value="{{tag.tag_name}}" checked> {{tag.tag_name}}<br>
                        {% else %}
                            <input type="checkbox" name="tag" value="{{tag.tag_name}}" > {{tag.tag_name}}<br>
                        {% endif %}
                    {% endfor %}
                </div>            
                <h3>Категория</h3>
                <ul id="id_category">
                    {% for section in sections %}
                        {% if article_section.id == section.id %}
                            <li><label for="id_category_{{ forloop.counter }}"><input type="radio" name="category" value="{{section.section_name_eng}}" required="" id="id_category_{{ forloop.counter }}" checked>{{section.section_name}}</label>
                        {% else %}
                            <li><label for="id_category_{{ forloop.counter }}"><input type="radio" name="category" value="{{section.section_name_eng}}" required="" id="id_category_{{ forloop.counter }}">{{section.section_name}}</label>
                        {% endif %}
                    {% endfor %}

                </ul>
                <br/>

                <h3>Название статьи</h3>
                <input name="title" value="{{article.title}}" type = "input" class = "form-control mb-2 mr-sm-2" id ="inlineFormInputName2" style = "width: 600px;" placeholder = "Заголовок статьи"> </input>
                <br/>
                <h3>Изображение статьи</h3>
                <img width="*" height="300px" src="{{MEDIA_URL}}{{article.preview_img}}"> </img>
                </br>
                <input type="file" name="first_image" class="" id="inlineFormInputName2" placeholder="Изображение" accept="first_image/*" > </input>
                <br/>
                <br/>
                <h3>Описание</h3>
                <textarea name="preview_text" cols="100" rows="3" type="text" class="form-control" id="inlineFormInputName2" placeholder="Описание" style="resize: none;" maxlength="300" required="">{{article.preview_text}}</textarea>
                <br/>
                <h3>Содержимое</h3>
                <textarea name="text" cols="180" rows="10" type="text" class="form-control" id="inlineFormInputName2" placeholder="Абзац" style="resize: none;" maxlength="1000" required="">{{article.text}}</textarea>

                {% for index in article.parts|get_range %}
                    {% for header in article_headers %}
                        {% if index == header.position%}
                            <div name="module={{header.position}}.header">
                                <br/>
                                <br/>
                                Заголовок
                                <br/>
                                <input value="{{header.text}}" type="input" name="{{header.position}}.header" class="form-control mb-2 mr-sm-2 {{header.position}}.header" id="inlineFormInputName2" style="width: 600px;" placeholder="Заголовок" maxlength="200" required="">
                                <button class="btn btn-danger" onclick = "destroy_object('module={{header.position}}.header');" >Удалить элемент</button>
                            </div>
                        {% endif %}
                    {% endfor %}

                    {% for paragraph in article_paragraphs %}
                        {% if index == paragraph.position%}
                            <div name="module={{paragraph.position}}.paragraph">
                                <br/>
                                <br/>
                                Абзац
                                <br/>
                                <textarea name="{{paragraph.position}}.paragraph" cols="40" rows="10" type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="resize: none;" placeholder="Абзац" maxlength="200" required="">{{paragraph.text}}</textarea>
                                <button class="btn btn-danger" onclick = "destroy_object('module={{paragraph.position}}.paragraph');" >Удалить элемент</button>
                            </div>
                        {% endif %}
                    {% endfor %}

                    {% for image in article_images %}
                        {% if index == image.position%}
                            <div name="module={{image.position}}.image">
                                <br/>
                                <br/>
                                Изображение
                                <br/>
                                <img width="*" height="300px" src="{{MEDIA_URL}}{{image.image}}"> </img>
                                <br/>
                                <input type="file" name="{{image.position}}.image" class="" id="inlineFormInputName2" placeholder="Изображение" accept="image/*" >
                                <br/>
                                <button class="btn btn-danger" onclick = "destroy_object('module={{image.position}}.image');" >Удалить элемент</button>
                            </div>
                        {% endif %}
                    {% endfor %}

                    {% for quote in article_quotes %}
                        {% if index == quote.position%}
                            <div name="module={{quote.position}}.quote">
                                <br/>
                                <br/>
                                Цитата
                                <br/>
                                <input value="{{quote.quote}}" type="input" name="{{quote.position}}.quote" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 1000px;" placeholder="Цитата" maxlength="200" required="">
                                <button class="btn btn-danger" onclick = "destroy_object('module={{quote.position}}.quote');" >Удалить элемент</button>
                            </div>
                        {% endif %}
                    {% endfor %}

                    {% for video in article_videos %}
                        {% if index == video.position%}


                            <div name="module={{video.position}}.video">
                                <br/>
                                <br/>
                                Видео
                                <br/>
                                <iframe width="500" height="300px" src="{{video.link}}"
                                    frameborder="0"
                                    allow="accelerometer; encrypted-media;  picture-in-picture"
                                    allowfullscreen>
                                </iframe>
                                <br/>
                                <br/>
                                <input value="{{video.link}}" type="input" name="{{video.position}}.video" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" style="width: 1000px;" placeholder="Ссылка на видео" maxlength="200" required="">
                                <button class="btn btn-danger" onclick = "destroy_object('module={{video.position}}.video');" >Удалить элемент</button>
                            </div>
                            <br/>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>


        </div>
        <br/>
        <div id="loading">
            <a class="p-link btn btn-warning" href="?upload=1&position=0">Добавить Заголовок</a>
            <a class="p-link btn btn-warning" href="?upload=2&position=0">Добавить Абзац</a> 
            <a class="p-link btn btn-warning" href="?upload=3&position=0">Добавить Изображение</a>
            <a class="p-link btn btn-warning" href="?upload=4&position=0">Добавить Цитату</a>
            <a class="p-link btn btn-warning" href="?upload=5&position=0">Добавить Видео</a>
        </div>
        <br/>
        <br/>
        <button class="btn btn-success" type="submit">Отправить</button>
    </Form>


    <script type="text/javascript">

        function ajax_pagination() {
        $('#loading a.p-link').each((index, elem) => {
        $(elem).click((e) => {
        e.preventDefault() // Останавливаем событие
        let page_url = $(elem).attr('href')

        $.ajax({
        url: page_url,
        type: 'GET',
        success: (data) => {
        //$('#list-elements').empty()
        $('#list-elements').append($(data).find('#uploading').html())

        $('#loading').empty()
        $('#loading').append($(data).find('#loading').html())        
        }
        })
        })
        })
        }

        $(document).ready(function() {
            ajax_pagination()
        })

        $(document).ajaxStop(function() {
            ajax_pagination()
        })         

        function destroy_object(name){
            $("div[name='" + name + "']").remove();
        }
    </script>

{% endblock %}

OnlineMedia/templates/form_creator/form_wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static '/bootstrap/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '/bootstrap/mystyle.css' %}" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class = "container bg-light">
      <div>
        <h1 class = "jumbotron bg-dark text-white font-weight-bold">
          Динамическая форма
        </h1>
        <p>
        <a href="{% url 'project_blog' project.id  %}" class="btn btn-warning btn-lg">Назад</a>
        </p>
          {% block content %}
          {% endblock %}
      </div>
    </div>
</body>
</html>