Maniac/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MarketPlace.urls")),
    path('market/', include("MarketPlace.urls")),
    path('catalogofartists/', include("CatalogOfArtists.urls")),
    path('onlinemedia/', include("OnlineMedia.urls")),
    path('account/', include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MarketPlace/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search-info/', views.search_info, name='search'),
    path('', views.list_category, name='list-category'),
    path('<int:id>/list-elements/', views.list_elements, name='list-elements'),
    path('<int:id>/list-elements/get-rating', views.get_rating, name='get-rating'),
    path('<int:id>/list-elements/info-element', views.info_element, name='info-element'),
]

MarketPlace/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse
from datetime import date
from uuid import uuid4

# *** Market Place ***

class Category(models.Model):
    """ Categories """
    category_name = models.CharField(max_length=300, unique=True, verbose_name='Название категории',
                                     help_text='( Введите название категории )')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.category_name


class City(models.Model):
    """ Cities """
    city_name = models.CharField(max_length=100, unique=True, verbose_name='Название города',
                                 help_text='( Введите название города )')

    class Meta:
        verbose_name = 'город'
        verbose_name_plural = 'города'

    def __str__(self):
        return self.city_name


class Element(models.Model):
    """ Elements """
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message='Phone number must be entered in the format: \'+999999999\'. Up to 15 digits allowed.')

    fk_category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, verbose_name='Категориия',
                                    help_text='( Выберите категорию из списка )')
    fk_city = models.ForeignKey('City', on_delete=models.SET_NULL, null=True, verbose_name='Город',
                                help_text='( Выберите город из списка )')

    element_name = models.CharField(max_length=300, unique=False, verbose_name='Название элемента',
                                    help_text='( Введите название элемента )')
    element_address = models.CharField(max_length=300, blank=True, verbose_name='Адрес элемента',
                                       help_text='( Введите адрес элемента )')
    element_preview_text = models.TextField(max_length=1000, blank=True, verbose_name='Краткое описание',
                                            help_text='( Введите краткое описание элемента )')
    element_description = models.TextField(blank=True, verbose_name='Подробное описание',
                                           help_text='( Введите подробное описание элемента )')
    element_preview_img = models.ImageField(upload_to='images/elements', height_field=None, width_field=None,
                                            max_length=100, blank=True, verbose_name='Картинка элемента')
    element_phone = models.CharField(validators=[ phone_regex ], max_length=17, blank=True,
                                     verbose_name='Номер телефона', help_text='( Номер телефона в формате: +999999999 )')
    element_email = models.EmailField(max_length=254, unique=True, blank=True, verbose_name='Электронный адрес элемента',
                                      help_text='( Добавьте адрес электронной почты )')
    fact_value_1 = models.CharField(max_length=100, blank=True, verbose_name='Значение факта для элемента',
                                    help_text='( Введите значение факта [1] для элемента )')
    fact_desc_1 = models.CharField(max_length=100, blank=True, verbose_name='Описание факта для элемента',
                                   help_text='( Введите описание факта [1] для элемента )')
    fact_value_2 = models.CharField(max_length=100, blank=True, verbose_name='Значение факта для элемента',
                                    help_text='( Введите значение факта [2] для элемента )')
    fact_desc_2 = models.CharField(max_length=100, blank=True, verbose_name='Описание факта для элемента',
                                   help_text='( Введите описание факта [2] для элемента )')
    fact_value_3 = models.CharField(max_length=100, blank=True, verbose_name='Значение факта для элемента',
                                    help_text='( Введите значение факта [3] для элемента )')
    fact_desc_3 = models.CharField(max_length=100, blank=True, verbose_name='Описание факта для элемента',
                                   help_text='( Введите описание факта [3] для элемента )')
    rating = models.IntegerField(default=0, null=True, blank=True)

    LPR_name = models.CharField(max_length=100, verbose_name='ФИО',
                                help_text='( Введите ФИО )')
    LPR_phone = models.CharField(validators=[ phone_regex ], max_length=17, blank=True,
                                 verbose_name='Номер телефона', help_text='( Номер телефона в формате: +999999999 )')
    LPR_email = models.EmailField(max_length=254, unique=True, blank=True, verbose_name='Электронный адрес элемента',
                                  help_text='( Добавьте адрес электронной почты )')
    LPR_link_vk = models.CharField(max_length=300, blank=True, verbose_name='Ссылка на ВК',
                                   help_text='( Добавьте ссылку на сообщество в ВК )')

    class Meta:
        verbose_name = 'элемент'
        verbose_name_plural = 'элементы'

    def __str__(self):
        return self.element_name


class LinkList(models.Model):
    """ Link list for element """
    fk_element = models.ForeignKey('Element', on_delete=models.CASCADE, null=True)
    element_link = models.CharField(max_length=300, blank=True, verbose_name='Ссылка на элемент')

    class Meta:
        verbose_name = 'ссылка на элемент'
        verbose_name_plural = 'ссылка на элемент'


class Gallery(models.Model):
    """ Gallery for element """
    fk_element = models.ForeignKey('Element', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/gallery', blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'галерея'
        verbose_name_plural = 'галерея'


class Poster(models.Model):
    """ Posters for element """
    fk_element = models.ForeignKey('Element', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/posters', blank=True, verbose_name='Изображение')
    date = models.DateField(null=True, blank=True, verbose_name='Дата')

    class Meta:
        verbose_name = 'афиша'
        verbose_name_plural = 'афиша'


class Tag(models.Model):
    """ Tags for element """
    fk_element = models.ForeignKey('Element', on_delete=models.CASCADE, null=True)
    tag_name = models.CharField(max_length=100, unique=True, verbose_name='Название тэга',
                                help_text='( Введите название тэга )')
    tag_desc = models.TextField(blank=True, verbose_name='Подробное описание',
                                help_text='( Введите подробное описание тэга )')

    class Meta:
        verbose_name = 'тэг'
        verbose_name_plural = 'тэги'

    def __str__(self):
        return self.tag_name

MarketPlace/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, City, Element, Gallery, Tag, Poster, LinkList

def list_category(request):
    categories = Category.objects.all()

    context = {
        'categories' : categories,
    }
    templates = 'category/list_category.html'

    return render(request, templates, context)

def search_info(request):
    name_ = request.GET.get('name', '')
    cat__ = request.GET.get('cat', '')
    city_ = request.GET.get('city', '')

    elements = None

    try: # Система поиска информации по модулю веб-сайта
        if name_ and cat__ and city_: # Если введены все данные
            category = Category.objects.get(category_name=cat__)
            city = City.objects.get(city_name=city_)
            elements = Element.objects.filter(element_name=name_).filter(fk_category=category).filter(fk_city=city).all().order_by('-id')
        elif name_ and cat__: # Если введено название элемента и выбрано название категории
            category = Category.objects.get(category_name=cat__)
            elements = Element.objects.filter(element_name=name_).filter(fk_category=category).all().order_by('-id')
        elif name_ and city_: # Если введено название элемента и введено название города
            city = City.objects.get(city_name=city_)
            elements = Element.objects.filter(element_name=name_).filter(fk_city=city).all().order_by('-id')
        elif cat__ and city_: # Если выбрано название категории и введено название города
            category = Category.objects.get(category_name=cat__)
            city = City.objects.get(city_name=city_)
            elements = Element.objects.filter(fk_category=category).filter(fk_city=city).all().order_by('-id')
        elif name_ and not cat__ and not city_: # Если введено только название элемента
            elements = Element.objects.filter(element_name=name_).all().order_by('-id')
        elif not name_ and cat__ and not city_: # Если выбрано только название категории
            category = Category.objects.get(category_name=cat__)
            elements = Element.objects.filter(fk_category=category).all().order_by('-id')
        elif not name_ and not cat__ and city_: # Если введено только название города
            city = City.objects.get(city_name=city_)
            elements = Element.objects.filter(fk_city=city).all().order_by('-id')
    except: elements = None

    context = {
        'elements' : elements,
    }
    templates = 'category/search.html'

    return render(request, templates, context)

def list_elements(request, id):
    category = Category.objects.get(id=id)
    elements = Element.objects.filter(fk_category=id).all().order_by('-id')

    page = request.GET.get('page')
    paginator = Paginator(elements, 3)

    try:
        elements = paginator.page(page)
    except PageNotAnInteger:
        elements = paginator.page(1)
    except EmptyPage:
        elements = paginator.page(paginator.num_pages)

    context = {
        'elements' : elements,
        'category' : category,
    }
    templates = 'elements/list_elements.html'

    return render(request, templates, context)

def get_rating(request, id):
    element = Element.objects.get(id=id)

    element.rating += 1
    if element.rating > 5:
        element.rating = 5
    element.save()

    templates = 'elements/list_elements.html'

    return render(request, templates)

def info_element(request, id):
    element = Element.objects.get(id=id)
    gallery = Gallery.objects.filter(fk_element=element).all()
    posters = Poster.objects.filter(fk_element=element).all().order_by('-date')[:3]
    links = LinkList.objects.filter(fk_element=element).all()

    context = {
        'element' : element,
        'gallery' : gallery,
        'posters' : posters,
        'links' : links,
    }
    templates = 'elements/info_element.html'

    return render(request, templates, context)

MarketPlace/templates/category/list_category.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Marketplace | RS{% endblock %}

{% block search %}
    <h1 class="hero__title">Маркетплейс<br><span>&laquo;Rock Stars&raquo;</span></h1>
    <h3 class="hero__subtitle">Онлайн-каталог организаций и&nbsp;частных лиц, оказывающих требуемые
        артистам услуги и&nbsp;предоставляющих концертные площадки</h3>
    <div class="hero__search">
        <form action="{% url 'search' %}" method="get" class="form hero__form">
            <div class="form__row">
                <div class="form__group">
                    <div class="form__sector">
                        <i class="fa fa-search"></i>
                        <input name="name" type="text" class="input form__input" placeholder="Название...">
                    </div>
                </div>
                <div class="form__group">
                    <div class="form__sector form__sector-leftborder">
                        <i class="fa fa-list"></i>
                        <select name="cat" class="select form__select">
                            <option value="">Все категории...</option>
                            {% for category in categories|dictsort:'category_name' %}
                                <option value="{{ category.category_name }}">{{ category.category_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form__group">
                    <div class="form__sector form__sector-leftborder">
                        <i class="fa fa-map-marker"></i>
                        <input name="city" type="text" class="input form__input" placeholder="Город...">
                    </div>
                </div>
                <div class="form__group">
                    <input name="search" type="submit" class="button form__button" value="Искать">
<!--                    <input name="search1"  value="Поиск">-->
<!--                    <a class="button form__button s-link" href="#">Поиск</a>-->
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block content %}
    <section class="section mp-categories">
        <div class="container">
            <div id="list-categories" class="mp-categories__wrapper">
                {% for category in categories|dictsort:'category_name' %}
                    <div class="mp-categories__column">
                        <a href="{% url 'list-elements' category.id %}" class="mp-categories__link">
                            <div class="mp-categories__item">
                                <div class="mp-categories__icon">
                                    <i class="fa fa-eye-slash"></i>
                                </div>
                                <div class="mp-categories__header">{{ category.category_name }}</div>
                                <div class="mp-categories__counter">{{ category.element_set.count }}</div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

MarketPlace/templates/category/search.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

    <section class="section mp-categories">
        <div class="container">
            <div id="list-elements" class="mp-categories__wrapper">
                {% if elements %}
                    {% for element in elements %}
                        <div class="mp-type__column">
                            <div class="mp-type__item">
                                <div class="mp-type__media">
                                    <a href="{% url 'info-element' element.id %}">
                                        <img src="{{ MEDIA_URL }}{{ element.element_preview_img }}" alt="">
                                    </a>
                                </div>
                                <div class="mp-type__content">
                                    <div class="mp-type__top">
                                        {% for tag in element.tag_set.all %}
                                            <div class="mp-type__tag">{{ tag.tag_name }}</div>
                                        {% endfor %}
                                        <div class="mp-type__city">{{ element.fk_city }}</div>
                                    </div>
                                    <div class="mp-type__header">
                                        <a href="{% url 'info-element' element.id %}">{{ element.element_name }}</a>
                                    </div>
                                    <div class="mp-type__description">{{ element.element_preview_text }}</div>
<!--                                    <div class="mp-type__rating">-->
<!--                                        <i class="fa fa-star"></i>-->
<!--                                        <i class="fa fa-star"></i>-->
<!--                                        <i class="fa fa-star"></i>-->
<!--                                        <i class="fa fa-star"></i>-->
<!--                                        <i class="fa fa-star-half"></i>-->
<!--                                    </div>-->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="mp-type__column">
                        <div class="mp-type__item">
                            <div class="mp-type__top">
                                <div class="mp-type__header">Ничего не найдено</div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}